@startuml anotation for file
/'
Автонумерация, алиасы для объектов, спец. значки для объектов (actor, database и т.п.)
title, skinparam, цвет фона участника, строковые переменные, примечания, activate/deactivate,
группировка участников в box (с выделением цветом).
Примечание: без alt и else.
'/
autonumber
skinparam sequence {
    MessageAlign left
    ParticipantPadding 100
}

title Оплаты товара в интернет-магазине с применением промокода
box #LightBlue
actor "Пользователь" as User order 10
participant "Учебный сайт" as Site order 20 #LimeGreen
end box

database "СУБД" as BD order 30
participant "Платежный шлюз" as Gate order 40 #LightSalmon
participant "Антифрод-система" as AntiFr order 50 #Khaki
!$pro = "промокода"
activate User
User -> Site : выбирает курс и\n нажимает кнопку "Купить"
activate Site
Site --> User: форма договора\n и чек-бокс $pro
note right: Возможный комментарий
User -> Site: заполняет форму договора
User -> Site: отмечает наличие $pro
Site --> User: поле $pro\n и кнопка "Проверить"
User -> Site: вводит промокод
User -> Site: нажимает кнопку "Проверить"

activate Site
Site -> BD: поиск $pro
activate BD
BD --> Site: результат проверки
deactivate BD
deactivate
Site -> Site: пересчет цены с учетом $pro
Site --> User: итоговая цена курса
User -> Site: оплачивает курс
Site -> Gate: регистрация заказа
deactivate Site
activate Gate
Gate --> User: платежная форма
Gate -> AntiFr: проверка заказа на мошенничество
AntiFr --> Gate: результаты проверки
User -> Gate: вводит реквизиты карты
activate Gate
Gate -> Gate: списание денег
Gate -> Gate: смена статуса платежа
Gate -> BD: смена статуса $pro
Gate --> Site: статус платежа
deactivate Gate
Site -> Site: обновление статуса платежа
activate Site
Site --> User: обновление страницы оплаты
deactivate Site
@enduml

