@startuml anotation for file
/'
автонумерация действий, алиасы, спец. значки для объектов (actor  и т.п.)
title, skinparam, цвет фона участника, строковые переменные,
HTML-цвета, примечания, группировка в alt, activate/deactivate,
группировка участников в box (в выделением цветом).
Примечание: без else.
'/
autonumber
skinparam sequence {
    MessageAlign left
    ParticipantPadding 100
}

title Оплаты товара в интернет-магазине с применением промокода
box "Юзер - Сайт" #LightBlue
actor "Пользователь" as User order 10
participant "Учебный сайт" as Site order 20 #LimeGreen
end box

database "СУБД" as BD order 30
participant "Платежный шлюз" as Gate order 40 #LightSalmon
participant "Антифрод-система" as AntiFr order 50 #Khaki
!$pro = "промокода"
activate User
User -> Site : выбирает курс и\n нажимает кнопку "Купить"
activate Site
Site --> User: форма договора\n и чек-боксом $pro
note right: Текст комментария к действию
User -> Site: вводит свои данные\n в форму договора
User -> Site: отмечает наличие $pro
Site --> User: поле ввода $pro\n и кнопку проверки
User -> Site: ввод $pro
User -> Site: нажимает кнопку "Проверить"

activate Site
Site -> BD: найти промокод
activate BD
BD --> Site: вернуть результат проверки
deactivate BD
deactivate
Site -> Site: пересчет цены с учетом $pro
Site --> User: показать итоговую цену курса
User -> Site: оплатить курс
Site -> Gate: зарегистрировать заказ
deactivate Site
activate Gate
Gate --> User: показать платежную форму

alt #Lavender the antifrost is connected
Gate -> AntiFr: проверить заказ на мошен-тво
AntiFr --> Gate: результаты проверки
end 

User -> Gate: ввести реквизиты карты
activate Gate
Gate -> Gate: списать деньги
Gate -> Gate: изменить статус платежа
Gate -> BD: изменить статус промокода
activate BD
Gate --> Site: вернуть статус платежа
deactivate BD
deactivate Gate
Site -> Site: обновить статус платежа
Site --> User: обновить страницу оплаты
@enduml

