@startuml

start

:Провалидировать\nвходные параметры;

if (Входные\nпараметры\nвалидны?) then (да)

:В задаче переписать параметры на новые;

else (нет)

endif

:Вернуть результат (task_id);

stop

@enduml
